version: '3'

services:
  uhyu-backend:
    build: .
    image: registry.pillow12360.world/u-hyu-be:latest
    container_name: uhyu-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_EXP: ${ACCESS_TOKEN_EXP}
      REFRESH_TOKEN_EXP: ${REFRESH_TOKEN_EXP}
      KAKAO_REST_API_KEY: ${KAKAO_REST_API_KEY}
      FRONT_BASE_URL: ${FRONT_BASE_URL}
      FASTAPI_RECOMMEND_HOST: http://uhyu-recommender:8000
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - uhyu-net

networks:
  uhyu-net:
    external: true
