spring:
  application:
    name: uhyu
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # 기본 프로필을 local로 설정

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}

app:
  frontend:
    url:
      local: http://localhost:5173
      prod: https://u-hyu.site

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: uhyu-server

openai:
  api:
    key: ${OPENAI_API_KEY}
  model: gpt-4o-mini