name: Deploy U-Hyu Backend

on:
  push:
    branches:
      - develop      # main에 push될 때 배포
  workflow_dispatch:  # 버튼 눌러서 수동 실행도 가능

jobs:
  deploy:
    uses: pillow-cloud/infra-ci/.github/workflows/spring-boot-ci.yml@main
    with:
      service_name: "u-hyu-be"
      registry_url: "localhost:5000"
      dockerfile: "./Dockerfile"               # 필요시 변경
      image_tag: "latest"                      # 나중에 git SHA로 바꿔도 됨
      compose_file: "./docker-compose.yml"     # 실제 사용하는 compose 경로
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}